name: Run Proxy Script on Data Update

on:
  push:
    paths:
      - data.txt  # Trigger the workflow only when 'data.txt' is modified
    branches:
      - main  # Run only on the main branch (or adjust to the branch you're using)

jobs:
  run_script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set your desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 4: Run the Python script
    - name: Run Proxy Script
      run: python insert_proxies.py  # Run your script
